import { Link } from 'react-router-dom';
import { ArrowRight, FolderOpen, CheckSquare, CalendarDays, FileText, BarChart3, Building2 } from 'lucide-react';
const modules=[['Projects','Keep project information organized in a shared workspace.',FolderOpen],['Tasks & schedules','Plan work, assign tasks, and track milestones.',CheckSquare],['Field reports','Record daily work, site notes, and reported issues.',FileText],['Financial overview','Review recorded project budgets and spending.',BarChart3],['Change orders','Organize scope changes and their recorded impacts.',CalendarDays],['Vendors & subcontractors','Keep business contacts and vendor information together.',Building2]];
export default function Home(){return <>
<section className="relative overflow-hidden pt-40 pb-24 px-6"><div className="absolute inset-0 pointer-events-none bg-[radial-gradient(ellipse_at_top_right,#60a5fa12,transparent_60%)]"/><div className="relative max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center"><div><p className="text-brand-lime text-xs font-semibold uppercase tracking-[.18em] mb-6">Construction management · In development</p><h1 className="text-5xl sm:text-6xl lg:text-7xl font-semibold text-white leading-[1.08] mb-7">A clearer view.<br/><span className="text-slate-400">A better workday.</span></h1><p className="text-lg text-slate-400 max-w-lg mb-9">Bring your projects, field reports, schedules, and budgets into one focused workspace.</p><div className="flex flex-wrap gap-3"><Link to="/contact" className="bg-brand-lime hover:bg-blue-300 text-brand-dark font-semibold rounded-xl px-6 py-3.5 flex items-center gap-3">Discuss your needs<ArrowRight size={17}/></Link><Link to="/dashboard" className="border border-slate-700 rounded-xl px-6 py-3.5 text-sm text-slate-200 hover:bg-white/5">Explore the demo</Link></div></div>
<div className="rounded-2xl border border-white/10 bg-[#111318] shadow-2xl overflow-hidden"><div className="px-6 py-4 border-b border-white/[.07] flex justify-between text-xs"><span className="text-slate-300 font-medium">Your construction workspace</span><span className="text-slate-500">Product overview</span></div><div className="p-6 sm:p-8"><div className="w-12 h-12 rounded-xl bg-brand-lime/10 flex items-center justify-center mb-6"><Building2 className="text-brand-lime"/></div><h2 className="text-2xl font-semibold text-white mb-2">Keep the work connected.</h2><p className="text-sm text-slate-400 mb-8">From planning to the daily field report.</p><div className="space-y-3">{modules.slice(0,4).map(([title,desc,Icon])=><div key={title} className="flex gap-4 p-4 rounded-xl bg-white/[.025] border border-white/[.04]"><Icon size={18} className="text-slate-400 mt-1 shrink-0"/><div><p className="text-sm font-medium text-slate-200">{title}</p><p className="text-xs text-slate-500 mt-1">{desc}</p></div></div>)}</div></div></div></div></section>
<section className="max-w-7xl mx-auto px-6 py-20 border-t border-white/[.06]"><p className="text-xs font-semibold text-brand-lime uppercase tracking-widest mb-4">A focused toolkit</p><h2 className="text-3xl sm:text-4xl font-semibold text-white mb-12">Built around your daily operations.</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{modules.map(([title,desc,Icon])=><div key={title} className="rounded-2xl border border-white/[.07] bg-brand-panel p-7"><Icon size={22} strokeWidth={1.5} className="text-brand-lime mb-6"/><h3 className="text-lg font-semibold text-white mb-3">{title}</h3><p className="text-sm text-slate-400">{desc}</p></div>)}</div></section>
<section className="max-w-7xl mx-auto px-6 pb-24"><div className="p-8 sm:p-12 rounded-2xl border border-white/[.07] bg-brand-panel flex flex-col md:flex-row justify-between items-start md:items-center gap-8"><div><h2 className="text-3xl font-semibold text-white mb-3">Help shape what comes next.</h2><p className="text-slate-400">Share the challenges your construction business faces.</p></div><Link to="/contact" className="px-6 py-3 rounded-xl bg-brand-lime text-brand-dark font-semibold text-sm shrink-0">Get in touch →</Link></div></section>
</>}
